### ISSUE TITLE
전공 과목 못불러오는 문제

### ISSUE THREAD

**Issue by puroong** [gomjellie/pysaint#20]
**Describe the bug**

전공 과목을 못불러오고 있습니다

**To Reproduce**
1. res = pysaint.get('전공', '2020', '2 학기')

**Expected behavior**
전공 과목 불러온 것을 res에 저장하기

**Screenshots**
![image](https://user-images.githubusercontent.com/15786615/98381675-8f349e80-208d-11eb-9bcb-f02962c2a951.png)

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser chrome
 - Version 83.0.4103.116

**Comment by gomjellie** [comment]
옴마이갓.... 유세인트 또 뭐 바꼈네;; 교직원 제발 일좀 그만했으면....

**Comment by gomjellie** [comment]
해결했읍니다 ^0^
